export const theme = {
    "light": {
        "background": "#eff1f5",
        "foreground": "#4c4f69",
        "card": "#e6e9ef",
        "card-foreground": "#4c4f69",
        "popover": "#dce0e8",
        "popover-foreground": "#4c4f69",
        "primary": "#FF7F00",
        "primary-foreground": "#F8FAFC",
        "secondary": "#F1F5F9",
        "secondary-foreground": "#0F172A",
        "muted": "#F1F5F9",
        "muted-foreground": "#64748B",
        "accent": "#F1F5F9",
        "accent-foreground": "#0F172A",
        "destructive": "#EF4444",
        "destructive-foreground": "#F8FAFC",
        "border": "#E2E8F0",
        "input": "#E2E8F0",
        "ring": "#020817",
        "warning":"#FFE100",
        "warning-foreground": "#4c4f69",
        "success":"#40A02B",
        "success-foreground": "#4c4f69",
        "info":"1E66F5",
        "info-foreground": "#4c4f69",
        "subtext":"#414141"
    },
    "dark": {
        "background": "#191724",
        "foreground": "#e0def4",
        "card": "#1f1d2e",
        "card-foreground": "#e0def4",
        "popover": "#26233a",
        "popover-foreground": "#e0def4",
        "primary": "#FF7F00",
        "primary-foreground": "#0F172A",
        "secondary": "#1E293B",
        "secondary-foreground": "#F8FAFC",
        "muted": "#1E293B",
        "muted-foreground": "#94A3B8",
        "accent": "#1E293B",
        "accent-foreground": "#F8FAFC",
        "destructive": "#7F1D1D",
        "destructive-foreground": "#F8FAFC",
        "border": "#1E293B",
        "input": "#1E293B",
        "ring": "#CBD5E1",
        "warning":"#FFE100",
        "warning-foreground":"#000000",
        "success":"#40A02B",
        "success-foreground":"#000000",
        "info":"1E66F5",
        "info-foreground":"#000000",
        "subtext":"#D9D9D9"
    }
}