export const theme = {
    "light": {
        "background": "#FAF9F8",
        "foreground": "#4C4F69",
        "card": "#F8F2F0",
        "card-foreground": "#212529",
        "popover": "#F4E7E0",
        "popover-foreground": "#212529",
        "primary": "#FF7F00",
        "primary-foreground": "FAF9F8",
        "secondary": "#4C4F69",
        "secondary-foreground": "#BCC0CC",
        "muted": "#FBFBFB",
        "muted-foreground": "#C9BCB5",
        "accent": "#F4EFEA",
        "accent-foreground": "#212529",
        "destructive": "#D44F3D",
        "destructive-foreground": "#FAF9F8",
        "info": "#C0EAF1",
        "info-foreground": "#163F67",
        "success": "#286983",
        "success-foreground": "#FAF9F8",
        "warning": "#FFD56A",
        "warning-foreground": "#FAF9F8",
        "border": "#EDEDED",
        "input": "#C9BCB5",
        "ring": "#E7E7E7",
        "subtext": "#4E4E4E",


    },
    "dark": {
        "background": "#0E0D0D",
        "foreground": "#FFFAF5",
        "card": "#171616",
        "card-foreground": "#FFFFFF",
        "popover": "#2E221B",
        "popover-foreground": "#FFFFFF",
        "primary": "#FF7F00",
        "primary-foreground": "#0E0D0D",
        "secondary": "#FFFAF5",
        "secondary-foreground": "#E0DEF4",
        "muted": "#040404",
        "muted-foreground": "#514335",
        "accent": "#1C1611",
        "accent-foreground": "#FFFFFF",
        "destructive": "#E2766F",
        "destructive-foreground": "#0E0D0D",
        "info": "#102F33",
        "info-foreground": "#6BB2FA",
        "success": "#A2D37B",
        "success-foreground": "#0E0D0D",
        "warning": "#4A3115",
        "warning-foreground": "#FF9820",
        "border": "#1F1D1C",
        "input": "#514335",
        "ring": "#1F1D1C",
        "subtext": "#B4A590",
    }
}