name: Release @a2apoint.com/tailwind-theme

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/tailwind-theme/**"

jobs:
  setup-bump-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Export token
        run:  |
          export BOT_GITEA_TOKEN=${{ secrets.BOT_GITEA_TOKEN }}
          echo $BOT_GITEA_TOKEN
      
      - name: Install dependencies
        run: yarn install

      - name: Configure git
        run: |
          git config --global user.email "gitea.bot@example.com"
          git config --global user.name "gitea.bot"

      - name: Build package
        run: |
          cd packages/tailwind-theme
          yarn build
      
      - name: Bump version
        run: |
          cd packages/tailwind-theme
          yarn version --patch

      - name: Publish package
        run: |
          cd packages/tailwind-theme
          npm publish
          
      - name: Push version bump
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          author_name: 'gitea.bot'
          author_email: 'gitea.bot@example.com'
          message: 'chore: bump version for @a2apoint/tailwind-theme'
