version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: directus
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  directus:
    image: a2apoint-directus:latest
    ports:
      - "8055:8055"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8055/server/health || exit 1
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  client:
    image: a2apoint-client:latest
    ports:
      - "3000:3000"
    depends_on:
      directus:
        condition: service_healthy

  nginx:
    image: a2apoint-nginx:latest
    depends_on:
      directus:
        condition: service_healthy
    ports:
      - "80:80"
