export const tailwindColors = {
    light: {
        background: '#FFFFFF',
        foreground: '#2D3748',
        card: '#FFFFFF',
        cardForeground: '#2D3748',
        popover: '#FFFFFF',
        popoverForeground: '#2D3748',
        primary: '#4A5568',
        primaryForeground: '#FFFFFF',
        secondary: '#CBD5E0',
        secondaryForeground: '#2D3748',
        muted: '#E2E8F0',
        mutedForeground: '#718096',
        accent: '#E2E8F0',
        accentForeground: '#2D3748',
        destructive: '#BF616A',
        destructiveForeground: '#FFFFFF',
        border: '#CBD5E0',
        input: '#CBD5E0',
        ring: '#FFFFFF',
        radius: '0.5rem',
    },
    dark: {
        background: '#2D3748',
        foreground: '#E2E8F0',
        card: '#2D3748',
        cardForeground: '#E2E8F0',
        popover: '#2D3748',
        popoverForeground: '#E2E8F0',
        primary: '#E2E8F0',
        primaryForeground: '#2D3748',
        secondary: '#6B7280',
        secondaryForeground: '#E2E8F0',
        muted: '#4A5568',
        mutedForeground: '#CBD5E0',
        accent: '#4A5568',
        accentForeground: '#E2E8F0',
        destructive: '#BF616A',
        destructiveForeground: '#FFFFFF',
        border: '#4A5568',
        input: '#4A5568',
        ring: '#1A202C',
        radius: '0.5rem',
    },
};
