import requests

locations = [
    "Palm Jebel Ali",
    "Downtown",
    "Business Bay",
    "Dubai Marina",
    "Palm Jumeirah",
    "Emaar Beachfront",
    "MBR City - Meydan",
    "Dubai Creek Harbour",
    "Dubai Hills Estate",
    "Damac Hills",
    "Damac Hills II (Akoya)",
    "Al Barari",
    "Al Barsha",
    "Al Furjan",
    "Al Ghadeer",
    "Al Habtoor City",
    "Al Jaddaf",
    "Al Marjan Island",
    "Al Safa",
    "Al Sufouh",
    "Alreeman",
    "Arabian Ranches",
    "Arjan - Dubailand",
    "Barsha Heights",
    "Bluewaters Island",
    "City Walk",
    "DHCC - Dubai Healthcare City",
    "DMC - Dubai Maritime City",
    "DSO - Dubai Silicon Oasis",
    "Damac Lagoons",
    "Dubai Harbour",
    "Dubai International City",
    "Dubai International Financial Centre | DIFC",
    "Dubai Investments Park | DIP",
    "Dubai Islands",
    "Dubai Production City | IMPZ",
    "Dubai South",
    "Dubai Sports City",
    "Dubai Studio City",
    "Dubailand",
    "Emaar South",
    "Emirate of Abu Dhabi",
    "Emirate of Ajman",
    "Emirate of Ras Al Khaimah",
    "Emirate of Sharjah",
    "JBR - Jumeirah Beach Residence",
    "JLT - Jumeirah Lake Towers",
    "JVC - Jumeirah Village Circle",
    "JVT - Jumeirah Village Triangle",
    "Jebel Ali Village",
    "Jumeirah",
    "Jumeirah Bay Jumeirah Golf Estates",
    "Jumeirah Islands",
    "Jumeirah Pearl",
    "Liwan",
    "Maryam Island",
    "MJL - Madinat Jumeirah Living",
    "Meadows",
    "Mina Rashid",
    "Motor City",
    "Mudon",
    "Nad Al Sheba",
    "Port De La Mer",
    "Saadiyat Grove",
    "Saadiyat Island",
    "Sobha Hartland",
    "Sobha Hartland 2",
    "The Heart Of Europe",
    "The Valley",
    "Tilal Al Ghaf",
    "Town Square",
    "Uptown",
    "Warsan First",
    "World Islands",
    "Yas Island",
    "Za'abeel",
    "Zayed City",
]

payload = []

for location in locations:
    payload.append({
        "title": location,
        "type": "group"
    })

token = "FcohKLOEi_mx_AyXLRwtoQ2PkeyhaQoU"
url = "https://dashboard.a2apoint.com"

res = requests.post(f"{url}/items/rooms", headers={"Authorization": f"Bearer {token}"}, json=payload)
print(res.json())
