name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      
      - name: Build Docker images
        run: bash .github/scripts/releases.sh

      - name: Create Tarball
        run: tar -czf deployment-artifacts.tar.gz -C .github/releases .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: deployment-artifacts.tar.gz
          path: deployment-artifacts.tar.gz
