name: Release

on:
  push:
    tags: 
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Build Docker images
        run: bash .github/scripts/releases.sh

      - name: Create Tarball
        run: tar -czf deployment-artifacts.tar.gz -C .github/releases .

      - name: Initialize release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Create Release
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: deployment-artifacts.tar.gz
          release-url: ${{ steps.create_release.outputs.upload_url }}
